/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class E_UI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(E_UI.class.getName());

    private DefaultTableModel mdNhanVien;
    private DefaultTableModel mdQuanLy;
    private List<CanBo> listCanBo = new ArrayList<>();
    
    public E_UI() {
        initComponents();
        initTable();
        
        cbNhanVien.setSelected(true);
        tvNdt_hscv.setText("Nganh dao tao");
        handleClickable();
    }
    
    private void handleSaveToFile(){
        try(BufferedWriter writer = new BufferedWriter(new FileWriter("Canbo.txt"))){
            for(CanBo cb : listCanBo){
                writer.write(cb.toString());
                writer.write("\n");
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Co loi xay ra trong qua trinh luu file");
        }finally{
            JOptionPane.showMessageDialog(null, "Luu file thanh cong");
        }
    }
    
    
    private void handleClickable(){
        
        cbNhanVien.addActionListener((v) -> {
            tvNdt_hscv.setText("Nganh dao tao");
        });
        
        cbQuanLy.addActionListener((v) -> {
            tvNdt_hscv.setText("He so chuc vu");
        });
        
        btnSaveToFile.addActionListener((v) -> {
            handleSaveToFile();
        });
        
        btnSave.addActionListener((var v) -> {
            
            String ten = edtName.getText();
            String nameSinh = edtDate.getText();
            String gioiTinh = cbSex.getSelectedItem().toString();
            String diaChi = edtAddress.getText();
            double heSoLuong = 0.0;
            String hsl = edtHSL.getText();
            
            try{
                heSoLuong = Double.parseDouble(hsl);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Vui long nhap so vao muc He So Luong");
                edtHSL.requestFocus();
                return;
            }
            CanBo cb = null;
            if(cbNhanVien.isSelected()){
                String nganhDaoTao = edtNDT_HSCV.getText();
                cb = new NhanVien(ten, nameSinh, gioiTinh, diaChi, heSoLuong, nganhDaoTao);
                mdNhanVien.addRow(cb.toObject());
            }
            else{
                double heSoChucVu = 0.0;
                String hscv = edtNDT_HSCV.getText();
                try{
                    heSoChucVu = Double.parseDouble(hscv);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Vui long nhap so vao muc He So Chuc Vu");
                    edtNDT_HSCV.requestFocus();
                    return;
                }
                cb = new QuanLy(ten, nameSinh, gioiTinh, diaChi, heSoLuong, heSoChucVu);
                mdQuanLy.addRow(cb.toObject());
            }
            listCanBo.add(cb);
        });
        
    }

    private void initTable(){
        mdNhanVien = new DefaultTableModel(new Object[]{"Ho ten", "Nam sinh", "Gioi tinh", "Dia chi", "He so luong", "Nganh dao tao", "Luong"},0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        mdQuanLy = new DefaultTableModel(new Object[]{"Ho ten", "Nam sinh", "Gioi tinh", "Dia chi", "He so luong", "He so chuc vu", "Luong"},0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbNhanVien.setModel(mdNhanVien);
        tbQuanLy.setModel(mdQuanLy);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        edtHSL = new javax.swing.JTextField();
        cbNhanVien = new javax.swing.JRadioButton();
        cbQuanLy = new javax.swing.JRadioButton();
        edtNDT_HSCV = new javax.swing.JTextField();
        tvNdt_hscv = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLy = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ho ten");

        jLabel2.setText("Nam sinh");

        jLabel3.setText("Dia chi");

        jLabel4.setText("Gioi tinh");

        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu", "Khac" }));

        jLabel5.setText("He so luong");

        buttonGroup1.add(cbNhanVien);
        cbNhanVien.setText("Nhan vien");

        buttonGroup1.add(cbQuanLy);
        cbQuanLy.setText("Quan ly");

        tvNdt_hscv.setText("Nganh dao tao");

        btnSave.setText("Luu");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnSaveToFile.setText("Luu vao file");

        tbQuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho ten", "Nam sinh", "Gioi tinh", "Dia chi", "He so luong", "He so chuc vu", "Luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbQuanLy);

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho ten", "Nam sinh", "Gioi tinh", "Dia chi", "He so luong", "Nganh dao tao", "Luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edtNDT_HSCV)
                        .addComponent(cbQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edtHSL)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(edtAddress)
                        .addComponent(edtDate)
                        .addComponent(edtName)
                        .addComponent(cbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveToFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tvNdt_hscv, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbQuanLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tvNdt_hscv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edtNDT_HSCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new E_UI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbNhanVien;
    private javax.swing.JRadioButton cbQuanLy;
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtDate;
    private javax.swing.JTextField edtHSL;
    private javax.swing.JTextField edtNDT_HSCV;
    private javax.swing.JTextField edtName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTable tbQuanLy;
    private javax.swing.JLabel tvNdt_hscv;
    // End of variables declaration//GEN-END:variables
}
